# Generated by Django 3.2.16 on 2023-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
