# Generated by Django 3.2.16 on 2022-12-11 00:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shares',
            unique_together={('owner', 'post')},
        ),
    ]
