# Generated by Django 3.2.16 on 2023-01-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_alter_shares_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shares',
            unique_together=set(),
        ),
    ]
