# Generated by Django 3.2.16 on 2023-01-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_share'),
        ('shares', '0004_alter_shares_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post'),
        ),
    ]
