# Generated by Django 3.2.16 on 2022-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/df4j1glpo/image/upload/v1671279356/default_profile_ogr78q.jpg', upload_to='images/'),
        ),
    ]
