# Generated by Django 3.2.16 on 2022-12-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/default_profile_ogr78q.jpg', upload_to='images/'),
        ),
    ]
