# Generated by Django 3.2.16 on 2023-01-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_share'),
        ('post_shares', '0002_auto_20230128_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postshare',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='postshare',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_share', to='posts.post'),
        ),
    ]
