# Generated by Django 3.2.16 on 2023-01-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocked', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocked',
            options={'ordering': ['owner']},
        ),
    ]
