# Generated by Django 3.2.16 on 2023-01-09 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blocked', '0003_auto_20230109_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
