# Generated by Django 3.2.16 on 2023-01-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocked', '0004_auto_20230109_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-created_at']},
        ),
    ]
