# Generated by Django 3.2.16 on 2023-01-16 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocked', '0005_alter_block_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL),
        ),
    ]
